version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Expõe a API
    environment:
      # Aponta para o arquivo SQLite que será salvo no volume
      - DATABASE_URL=file:/app/prisma/data.db
      - JWT_SECRET=SEU_SEGREDO_JWT_AQUI
    volumes:
      # Monta o volume 'sqlite_data' no diretório onde o Prisma
      # irá criar e acessar o arquivo 'data.db'.
      # Isso garante que o banco de dados persista.
      - sqlite_data:/app/prisma
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80" # Expõe o React (servido pelo Nginx)
    depends_on:
      # O frontend só inicia após o backend estar pronto
      - backend

volumes:
  # Define o volume nomeado para persistir o arquivo do SQLite
  sqlite_data: