name: Deploy Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      COMPOSE_PROFILES: sqlite
    steps:
      - uses: actions/checkout@v4
      - name: Docker compose up
        run: |
          docker compose pull || true
          docker compose up -d --build
